//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAirLineReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locker
    {
        public int LockerID { get; set; }
        public Nullable<int> LockerOrderID { get; set; }
        public string LockerPassword { get; set; }
        public int LockerStatusID { get; set; }
    
        public virtual LockerStatu LockerStatu { get; set; }
        public virtual WifiOrder WifiOrder { get; set; }
    }
}
