//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAirLineReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxFreeProductOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxFreeProductOrder()
        {
            this.TaxFreeProductOrderDetails = new HashSet<TaxFreeProductOrderDetail>();
        }
    
        public int TaxFreeProductOrderID { get; set; }
        public int AirLineID { get; set; }
        public int CouponID { get; set; }
        public int PaymentMethodID { get; set; }
        public decimal OrderAmount { get; set; }
    
        public virtual AirLine AirLine { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxFreeProductOrderDetail> TaxFreeProductOrderDetails { get; set; }
    }
}
